### PR TITLE
Fix readme instructions

### PR DESCRIPTION
**Pull request by orfeasa**

### CODE REVIEW

**Comment by bocekm** [comment]
Agreed. The wrong git command made me wonder what's wrong with my network connection.

**Comment by bocekm** [comment]
Also, where do I enable the extension in GNOME Tweaks? I don't see it there.

**Comment by bdaase** [comment]
@orfeasa Thanks!

**Comment by bdaase** [comment]
@bocekm You might need to log out and log back in again.

**Pull request merged**
